name = "tidy-by-tabb-admin-gateway"
main = "src/index.js"
compatibility_date = "2026-07-29"
workers_dev = false

routes = [
  { pattern = "www.tidybytabb.com/admin/api*", zone_name = "tidybytabb.com" }
]

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "tidy-by-tabb"
database_id = "e0c5e80b-2105-4353-b0d3-bc408e9dbef8"
