import{getPreviewUrl,normalizeRecord}from"./utils.js";import{toast,loading}from"./ui.js";
export class GalleryDrawer{
 constructor(api,onChanged){this.api=api;this.onChanged=onChanged;this.drawer=document.getElementById("galleryDrawer");this.backdrop=document.getElementById("drawerBackdrop");this.form=document.getElementById("galleryForm");this.save=document.getElementById("saveRecord");this.del=document.getElementById("deleteRecord");this.f={id:recordId,title:recordTitle,category:recordCategory,beforeImage,afterImage,comparisonImage,status:recordStatus,featured:recordFeatured};this.beforePreview=document.getElementById("beforePreview");this.afterPreview=document.getElementById("afterPreview")}
 bind(){drawerClose.onclick=()=>this.close();drawerCancel.onclick=()=>this.close();this.backdrop.onclick=()=>this.close();this.form.onsubmit=e=>this.submit(e);this.del.onclick=()=>this.remove();this.f.beforeImage.oninput=()=>this.preview(this.beforePreview,this.f.beforeImage.value,"before");this.f.afterImage.oninput=()=>this.preview(this.afterPreview,this.f.afterImage.value,"after")}
 open(record=null){this.current=record?normalizeRecord(record):null;drawerTitle.textContent=this.current?"Edit transformation":"Add transformation";this.del.hidden=!this.current;const r=this.current||{};this.f.id.value=r.id||"";this.f.title.value=r.title||"";this.f.category.value=r.category||"";this.f.beforeImage.value=r.beforeImage||"";this.f.afterImage.value=r.afterImage||"";this.f.comparisonImage.value=r.comparisonImage||"";this.f.status.value=r.published?"published":"draft";this.f.featured.checked=!!r.featured;this.preview(this.beforePreview,r.beforeImage,"before");this.preview(this.afterPreview,r.afterImage,"after");this.drawer.classList.add("is-open");this.drawer.setAttribute("aria-hidden","false");this.backdrop.hidden=false;document.body.classList.add("drawer-open")}
 close(){this.drawer.classList.remove("is-open");this.drawer.setAttribute("aria-hidden","true");this.backdrop.hidden=true;document.body.classList.remove("drawer-open");this.form.reset();this.current=null}
 payload(){return{title:this.f.title.value.trim(),category:this.f.category.value.trim(),beforeImage:this.f.beforeImage.value.trim(),afterImage:this.f.afterImage.value.trim(),comparisonImage:this.f.comparisonImage.value.trim(),published:this.f.status.value==="published",featured:this.f.featured.checked}}
 async submit(e){e.preventDefault();if(!this.form.reportValidity())return;loading(this.save,true);try{const res=this.current?await this.api.update(this.current.id,this.payload()):await this.api.create(this.payload());toast(res.message||"Saved.");this.close();await this.onChanged()}catch(err){toast(err.message,"error")}finally{loading(this.save,false)}}
 async remove(){if(!this.current||!confirm(`Delete "${this.current.title}"?`))return;loading(this.del,true,"Deleting…");try{const res=await this.api.delete(this.current.id);toast(res.message||"Deleted.");this.close();await this.onChanged()}catch(err){toast(err.message,"error")}finally{loading(this.del,false)}}
 preview(el,url,label){const src=getPreviewUrl(url,700);el.innerHTML=src?`<img src="${src}" alt="${label} image preview">`:`<div class="preview-empty">No ${label} image selected</div>`}
}
