import{escapeHtml,getPreviewUrl,normalizeRecord}from"./utils.js";
export class GalleryController{
 constructor(onEdit){this.records=[];this.onEdit=onEdit;this.grid=document.getElementById("galleryGrid");this.empty=document.getElementById("galleryEmpty");this.loading=document.getElementById("galleryLoading");this.search=document.getElementById("gallerySearch");this.category=document.getElementById("galleryCategory");this.status=document.getElementById("galleryStatus");this.recent=document.getElementById("dashboardRecent")}
 bind(){["input","change"].forEach(evt=>this.search?.addEventListener(evt,()=>this.render()));this.category?.addEventListener("change",()=>this.render());this.status?.addEventListener("change",()=>this.render())}
 setLoading(v){if(this.loading)this.loading.hidden=!v}
 setRecords(records){this.records=(records||[]).map(normalizeRecord);this.categories();this.stats();this.renderRecent();this.render()}
 categories(){const current=this.category?.value||"";const cats=[...new Set(this.records.map(r=>r.category).filter(Boolean))].sort();if(this.category){this.category.innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option value="${escapeHtml(c)}">${escapeHtml(c)}</option>`).join("");if(cats.includes(current))this.category.value=current}}
 stats(){const published=this.records.filter(r=>r.published).length;const values={statTotal:this.records.length,statPublished:published,statDrafts:this.records.length-published,statFeatured:this.records.filter(r=>r.featured).length};Object.entries(values).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v})}
 filtered(){const q=(this.search?.value||"").toLowerCase();const c=this.category?.value||"";const s=this.status?.value||"";return this.records.filter(r=>(!q||r.title.toLowerCase().includes(q)||r.category.toLowerCase().includes(q))&&(!c||r.category===c)&&(!s||(s==="published"&&r.published)||(s==="draft"&&!r.published)||(s==="featured"&&r.featured)))}
 render(){this.setLoading(false);const rows=this.filtered();this.grid.innerHTML="";this.grid.hidden=!rows.length;this.empty.hidden=!!rows.length;rows.forEach(r=>{const card=document.createElement("article");card.className="gallery-card";const img=getPreviewUrl(r.comparisonImage||r.afterImage||r.beforeImage,800);card.innerHTML=`<button class="gallery-card-button"><div class="gallery-card-media">${img?`<img src="${escapeHtml(img)}" alt="${escapeHtml(r.title)}" loading="lazy">`:'<div class="gallery-placeholder">No preview image</div>'}</div><div class="gallery-card-body"><h3>${escapeHtml(r.title||"Untitled")}</h3><p>${escapeHtml(r.category||"Uncategorized")}</p><div class="badge-row"><span class="badge ${r.published?"badge-published":""}">${r.published?"Published":"Draft"}</span>${r.featured?'<span class="badge badge-featured">Featured</span>':""}</div></div></button>`;card.querySelector("button").onclick=()=>this.onEdit(r);this.grid.appendChild(card)})}
 renderRecent(){if(!this.recent)return;const rows=[...this.records].sort((a,b)=>new Date(b.updated||b.created)-new Date(a.updated||a.created)).slice(0,5);this.recent.innerHTML=rows.length?rows.map(r=>{const img=getPreviewUrl(r.afterImage||r.beforeImage,240);return`<button class="recent-item gallery-card-button" data-id="${escapeHtml(r.id)}"><div class="recent-thumb">${img?`<img src="${escapeHtml(img)}" alt="">`:""}</div><div class="recent-copy"><strong>${escapeHtml(r.title||"Untitled")}</strong><span>${escapeHtml(r.category||"Uncategorized")}</span></div><span class="badge ${r.published?"badge-published":""}">${r.published?"Published":"Draft"}</span></button>`}).join(""):'<div class="empty-state">No transformations yet.</div>';this.recent.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>this.onEdit(this.records.find(r=>r.id===b.dataset.id)))}
}
